module.exports = {
    /**
     * Inline source maps, generated by TypeScript compiler, will be used for code coverage.
     */
    devtool: 'inline-source-map',

    verbose: true,

    resolve: {
        extensions: ['', '.ts', '.js', '.scss', '.html'],
        modulesDirectories: ['node_modules', 'src']
    },

    module: {
        loaders: [
            /**
             * Enable inline source maps for code coverage report.
             *
             * See project repository for details / configuration reference:
             * https://github.com/s-panferov/awesome-typescript-loader
             */
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader?sourceMap=false,inlineSourceMap=true,allowUnreachableCode=true']
            },
            {test: /\.json$/, loader: 'json-loader'},
            {test: /\.html$/, loader: 'html-loader'},
            {test: /\.css$/, loaders: ['to-string-loader', 'css-loader']}
        ],
        postLoaders: [
            /**
             * Instruments TS source files for subsequent code coverage.
             * See https://github.com/deepsweet/istanbul-instrumenter-loader
             */
            {
                test: /\.ts$/,
                loader: 'istanbul-instrumenter-loader',
                exclude: [
                    'node_modules',
                    /\.(e2e|spec)\.ts$/
                ]
            }
        ]
    }
};
